### ISSUE TITLE
没有足够的数值去解包

### ISSUE THREAD

**Issue by BothCats** [OneYearIsEnough/PaddleOCR-Recog-LmdbDataset-Conversion#3]
Traceback (most recent call last):/train.txt : 2000/6505 completed.
  File "make_lmdb.py", line 106, in <module>
    convert2lmdb(
  File "make_lmdb.py", line 73, in convert2lmdb
    relative_img_path, label = lines[i].split(delimiter_dict[delimiter], 1)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by BothCats** [comment]
可以看到我已经成功了2000文件了，但是为什么还会报错呢
